In [13]:
## 기본적인 집계 함수 
import numpy as np
arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)
print(np.sum(arr))
print(arr.sum())
print(np.cumsum(arr)) ## 누적시켜서 한개의 항씩 표현 
print(np.max(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.std(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.log10(arr))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
66
[ 0  1  3  6 10 15 21 28 36 45 55 66]
11
5.5
0
3.452052529534663
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
[[      -inf 0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125 0.84509804]
 [0.90308999 0.95424251 1.         1.04139269]]


C:\Users\student\Anaconda3\envs\CPU_ENV\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in log
  del sys.path[0]
C:\Users\student\Anaconda3\envs\CPU_ENV\lib\site-packages\ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in log10
  


In [30]:
# 축개념을 이해해 보자 
# 위의 집계 합수를 이용할 때  axis개념을 사용한다.
# 만약 axis를 명시하지 않으면 axis를 None 으로 설정하고 
# 대상범위를 전체 어레이로 지정

# 1차원 ndarray
arr = np.arange(1,10,1)
print(arr)
print(arr.sum(axis = 0)) # axis 가 0 이면 -> 이 방향을 지칭한다.
                        # axis 가 1이면 -> 행방향을 지칭한다

#2차원 어레이    
arr1 = arr.reshape(3,3).copy()
print(arr1)
print(arr1.sum(axis = 0))   # axis가 0 이면 열 고정 행의 합 (1행1열, 2행1열,3행1열) 
print(arr1.sum(axis = 1))   # axis가 1 이면 행 고정 열의 합 (1행1열,1행2열,1행 3열)

# 3차원 어레이 
arr2 = np.arange(0,20,1).reshape(2,2,5).copy()
print(arr2)
print(arr2.sum(axis = 0))   # 행 열 고정 차원의 합 
print(arr2.sum(axis = 1))   # 차원 고정 열 고정 행의 합 
print(arr2.sum(axis = 2))   # 차원고정 행고정 열의 합

[1 2 3 4 5 6 7 8 9]
45
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
[[10 12 14 16 18]
 [20 22 24 26 28]]
[[ 5  7  9 11 13]
 [25 27 29 31 33]]
[[10 35]
 [60 85]]


In [48]:
## 응용 
np.random.seed(1)
arr = np.random.randint(1,10,(2,5))
print(arr)
print(len(arr[arr>5]))    # 곰같은 우직한 새끼 맨날 하던것만 해 
print((arr>5).sum())     # 마스크 이용하는 섹시한 방법 
arr[arr>5].size         # 불리안 인덱싱 이용 하는 섹시한 방법



[[6 9 6 1 1]
 [2 8 7 3 5]]
5
5
[6 9 6 1 1]


In [47]:
# Delete( ) 함수는 axis를 기준으로 행과 열을 삭제 
# axis를 지정하지 않으면 1차배열로 변환한 후 해당 요소를 삭제 
# 원본은 유지; 하고 삭제된 복사본을 리턴

arr= np.arange(0,12,1).reshape(3,4).copy()
print(arr)
# axis를 지정하지 않고 delete
result = np.delete(arr,1)   # 1차 배열로 변환햇다아  그다음에 원소가 1인것만 지운다 

result = np.delete(arr,1,axis=0)  # 1번 행을 삭제

result = np.delete(arr,1,axis=1)   # 1번 열을 삭제 
print(result)
# 느낌이 그럼 3차원이면 0일경우 차원 삭제 1일경우 행 2일경우 열 --> 가설 검증완료  사실임


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
