In [5]:
import numpy as np 
arr = np.arange(10,20,1)

for i in arr: # 데이터만 추출하는 for
    print ("데이터는 {}".format(i))
for idx,data in enumerate(arr):    # 인덱스 뽑아내기 
    print("index : {} data :{}".format(idx,data))

데이터는 10
데이터는 11
데이터는 12
데이터는 13
데이터는 14
데이터는 15
데이터는 16
데이터는 17
데이터는 18
데이터는 19
index : 0 data :10
index : 1 data :11
index : 2 data :12
index : 3 data :13
index : 4 data :14
index : 5 data :15
index : 6 data :16
index : 7 data :17
index : 8 data :18
index : 9 data :19


In [39]:
## 슬라이싱 ----> 이건 인덱싱이 아니다 nparray로 output이 나온다 
arr = np.arange(0,6,1)
print(arr[-1:]) # 맨 마지막 요소만 슬라이싱
print(arr[1:3])
print(arr[1::2])

arr = np.arange (0,12,1).reshape(3,4).copy()
print (arr)
print(arr[1,2])
print(arr[:,0])   # 한개는 넘파이 어레이 한개는 인덱싱그래서 1차원
print(arr[:,0:1]) # 두개다 슬라이싱 이니까 2차원 
print(arr[1:3,1:3].ravel())

[5]
[1 2]
[1 3 5]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[0 4 8]
[[0]
 [4]
 [8]]
[ 5  6  9 10]


In [90]:
# Boolean indexing & Fancy indexing 
# 불리안 인덱싱은 mask를 이용해서 배열 각 요소의 선택여부를 True or False 로 지정해서 True 요소만 선택하는 방식
np.random.seed(3)
arr = np.random.randint(0,9,(10,))
#print(arr)

# 짝수만 추출해보기
print(arr[arr %2==0])
# 레퍼런스 
# 조건에 맞는 마스크를 만들어 
print(arr%2==0)

#Fancy indexing 
# indexing 할때 배열을 이용해서 배열 요소를 찾는 방식

arr = np.arange(0,12,1).reshape(3,4).copy()
print(arr)
print(arr[2,2]) #인덱싱
print(arr[1:2,2]) # 슬라이싱

print(arr[[0,2],1:]) # 0행과 2행 두개를 지칭 
print(arr[[1,2],[1,2]]) # 1행 1열과 2행2열을 뽑는다
# 5 6 9 10 뽑으려면?
print(arr[[1,2],1:3])   # 하나는 팬시하고 하나는 슬라이싱 해야 댄다 
# 굳이 하자면?
print(arr[[1,2]][:,[1,2]]) # 앞쪽에서 인덱싱 한걸 다시 인덱싱
# 방법 2 
print(arr[np.ix_([1,2],[1,2])]) 

[8 8 8 0 6]
[ True False  True  True  True False False False False  True]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
10
[6]
[[ 1  2  3]
 [ 9 10 11]]
[ 5 10]
[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]


In [99]:
# array 의 연산
# 벡터의 연산과 비슷 
np.random.seed(1)
arr1= np.arange(1,7,1).reshape(2,3).copy()
arr2=np.random.randint(1,10,(2,3))
print(arr1)
print(arr2)

print(arr1+arr2)
print(arr1*arr2)
print(arr1+10) # 원래는 타입이 안맞아서 안되야 한다 
                # 그런데 이경우 스칼라를 broadcasting 시켜서 진행한다. 
                # 브로드캐스팅이랑? 주어진 어레이에 맞춰서 행과 열을 늘려준다. 넘파이에서 가능 
arr3 = np.array([1,2,3])
print(arr1+arr3) # arr3이 브로드캐스팅 되엇다. 
## 브로드캐스팅 안되는 형태일경우 에러 
arr4 = np.array([1,2])
#print(arr1+arr4)

[[1 2 3]
 [4 5 6]]
[[6 9 6]
 [1 1 2]]
[[ 7 11  9]
 [ 5  6  8]]
[[ 6 18 18]
 [ 4  5 12]]
[[11 12 13]
 [14 15 16]]
[[2 4 6]
 [5 7 9]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 