In [35]:
## 11월 19일 
## 넘파이 (numerical python)
## nd array라는 자료 구조를 사용한다. 

# array 연속적으로 할당되는 같은 데이터 타입의 데이터를 저장할 수 있는 구조 

import numpy as np 

arr = np.array([[1,2],[12,34],[1,4]])# 인자로는 리스트 혹은 튜플을 넣어준다


# python 에서 빌트 인 타입 
## int float bool str list tuple dict set 
## => 이 데이터 타입이라고 알고 있던 것들이 실제로는 
## int 라는 클래스로 존재  타입 함수로 클래스를 알아보자 
print ( type(arr))
print(arr.ndim) ## 차원의 수 
print(arr.shape)  ## 차원수 각 차원당 원소의 수 
#arr.reshape(1,4) # 이 방법을 이용하자 shape는 되도록 이용 ㄴ


print(arr.size) ## 전체 원소의 개수 
print(len(arr)) # 1차원의 갯수 예제는 보면 3개가 잇는거 제일 큰 괄호 안에 있는것 
myList=([[12,34],[1,2]])
arr1 = np.array(myList,dtype= np.float64)
print(arr1)


# 다양한 생성방법 
arr = np.zeros([2,2])
print(arr)
print(np.eye(3))
print(np.ones([2,1]))
## zeros ones empty full 
np.arange(0,8,1)
## arange ,np.linspace

# random 기반의 함수들  => 4가지 



<class 'numpy.ndarray'>
2
(3, 2)
6
3
[[12. 34.]
 [ 1.  2.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1.]
 [1.]]


array([0, 1, 2, 3, 4, 5, 6, 7])

In [57]:
# 넘파이 
## shape 조절해서 내가 원하는 형태의 어레이로 만들어보세요 
import numpy as np 
arr = np.arange(1,13,1)
arr1 = arr.reshape(4,3)
print((arr1))
## reshape 이용 하면 view가 만들어진다. 
## 데이터를 그냥 4 행 3열로 보겟다ㅣ는거지 데이터를 바꾼것이 아니다. 
arr[1]=100
print(arr)
print((arr1[2][2])) ## 그렇기 때문에 원본이 바뀌면 뷰도 바뀐다.
arr1[2][2] = 452
print(arr)
print((arr1))         ## 뷰를 바꿔도 원본이 바뀌는 것이다 .그냥 틀이기 때문 
print(arr1.base is arr) # 원본이냐? 
print(arr1.base == arr)  # 각각의 칸끼리 비교한다 각각의 요소 끼리 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[  1 100   3   4   5   6   7   8   9  10  11  12]
9
[  1 100   3   4   5   6   7   8 452  10  11  12]
[[  1 100   3]
 [  4   5   6]
 [  7   8 452]
 [ 10  11  12]]
True
[ True  True  True  True  True  True  True  True  True  True  True  True]


In [73]:
arr = np.arange(0,12,1)
#print(arr)
arr1 = arr.reshape(4,3).copy()    # 새로운 어레이를 생성
#print (arr1)

#arr2 = arr.reshape(5,3)  ## 에러 형태가 맞지않음
arr2 = arr.reshape(2,-1)   ## -1 은 앞에 채우고 나머지 다 뒤로 밀어넣어 라는 의미임  자동 채움 
#print(arr2)
arr3 = arr.reshape(-1,3)    ## -1 은 자동 계산 
#print(arr3)
################################################################ 다차원을 1차원으로 
arr4 = np.arange(0,100,1).reshape(5,-1).copy()
print(arr4)
arr5= np.ravel(arr4)     ##########다차원을 1차원으로 만드는 함수 
print (arr5)



[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [85]:
# resize 함수 reshape 과 상당히 유사 
## reshape 은 형태가 맞지 않으면 변경시 에러가 난다
# 리 사이즈는 안남

arr= np.arange(0,10,1)

# resize 를 이용하는 첫번째 방법 
#np.resize(arr,(8,2))   # 범위가 넘어가는 것은 처음부터 반복
                        # 변경값을 리턴 해줌  원본은 변경없음

arr= np.arange(0,10,1) # 원본을 바꾸고 싶다
result = arr.resize(2,3)   # 원본이 바뀌지 리턴되지 않는다.
print(arr)



[[0 1 2]
 [3 4 5]]


In [124]:
# numpy array 를 가로 혹은 세로 방향으로 붙여보자 
## 2행 3열 짜리 ndarray 를 생성 정수로 생성 랜덤하게  균등분포 0에서 10사이
np.random.seed(3)
arr= np.random.randint(0,11,(2,3))
print(arr)
# 가로방향으로 결합 
# 행의개수가 같아야 합니다.
arr1= np.random.randint(0,10,(2,3))
print(arr1)
np.hstack((arr,arr1))  # 옆으로 붙이기    행결합
np.vstack((arr,arr1))  # 위로 붙이기    열결합 
print(arr1[0:2,0:1])

[[10  8  9]
 [ 3  8  8]]
[[0 5 3]
 [9 9 5]]
[[0]
 [9]]
